### ISSUE TITLE
Visual review

### ISSUE THREAD

**Issue by krrisis** [Giveth/website#14]
TOP NAV
Consistency with text, change naming, see previous issue
Add 'About' subpage (see further)

JOIN SLACK
- yellow button 'sticks' to the purple on a 13" screen, but is ok on 17"

GITHUB
- text under github coding is not outlined in the center on a 17" and on the left on a 13"

TABLE
- I think the benefits table is GREAT and SHOULD be in there but it's just too big here. 
Proposal: Replace the table by 5 bullet points: 'Giveth is Transparent, Giveth is Secure, Giveth is Flexible etc.' You put a little arrow under each that expands to more text under each title when clicked. This text is every time two bullet points: 'For Givers' and 'For Campaigns' with explanation (but I think this needs to be 'For Makers' -> see previous issue). By default non expanded or first is open, rest closed. To be tested.

GIVETH DAC
- text is quite long on all screens except for 17", I'd only keep the first paragraph and add a 'Read More...', this one links to a separate page which is /About. Here you add the text of the Medium Post 'Presenting the Giveth DAC' with the 3 headers AND the visual of the team making us more human, approachable. --> https://medium.com/giveth/giveth-introduces-decentralized-altruistic-communities-dacs-d1155a79bdc4

**Comment by geleeroyale** [comment]
Implemented most of these changes. Thanks @krrisis !
