### ISSUE TITLE
Missing Links 

### ISSUE THREAD

**Issue by krrisis** [Giveth/website#15]
OUR PROJECTS

- Add a 'Discover' or a 'Try it yourself' or sth similar button under both texts, which takes you directly to these subsites (//topnav). 

OUR CONTRACTS 

- Add a 'Read more...' under MiniMe going here https://medium.com/giveth/the-minime-token-open-sourced-by-giveth-2710c0210787
- Add a 'Read more...' under Vault going here https://medium.com/giveth/the-vault-contract-open-sourced-by-giveth-fe2261f7b91b
- Add a 'Read more...' under Liquid Pledging going here https://github.com/Giveth/liquidpledging (soon to be replaced by a Medium post)
- Add a 'Read more...' under Milestone Payouts (Milestone Tracker?) going here  https://github.com/Giveth/milestonetracker

GIVETH DAC
- see previous issue

JOIN US
- Add link to Medium https://medium.com/giveth
- Add link to Reddit https://www.reddit.com/r/Giveth

**Comment by geleeroyale** [comment]
Done
