### ISSUE TITLE
HTTP site is still operational.

### ISSUE THREAD

**Issue by mex20** [Giveth/website#18]
The HTTP (non-HTTPS) site for the website and also the wiki are still accessible via manual entry into the browser and as entries in a Google search. There should be no portion of the website served in HTTP. Also the slack.giveth.io page does not currently have HTTPS.

**Comment by geleeroyale** [comment]
Hey mex! I would really like to alleviate this. Do you want to join our slack for dicussion? [slack.github.io](http://slack.giveth.io) ... you can find the website community at the #_website_circle channel.
