### ISSUE TITLE
Replace hero picture

### ISSUE THREAD

**Issue by Grace-Giveth** [Giveth/website#23]
In view of preserving an image of fun, friendly, innovative, inclusive - this picture is better suited for the landing page. 
![istock-479293082-2](https://user-images.githubusercontent.com/18598517/31706491-6fab4910-b3e9-11e7-9287-82cfd821ae52.jpg)

**Comment by geleeroyale** [comment]
Looks awesome! I like how it forms this geometric structure with the current hero elements. Nice find!
