### ISSUE TITLE
Make team video upload minipage

### ISSUE THREAD

**Issue by geleeroyale** [Giveth/website#26]
**Wall of Fame**

**The goal is to have a minipage that shows the individual Unicorn progress for the past week as a video.** 

We want to use @eduadiez video uploader to achieve this. See the origin here: [https://github.com/eduadiez/MyCampaignVideos](https://github.com/eduadiez/MyCampaignVideos)

Requirements up for discussion:
- make it funky and fun
- it would be nice if we can keep it one page on desktop with minimal or no scrolling
- only allow video uploads and limit text display to allow for 'the wizards portrait gallery'

**Comment by GriffGreen** [comment]
eduadiez [12:04 PM] 
https://eduadiez.github.io/GivethVWOF/

The link always goes to the current week, so each week automatically starts in white.
You can always see a concrete week and make a upload to this with "+" (the format is weeknumber_month_year): https://eduadiez.github.io/GivethVWOF/41_10_2017
You can link to a specific video (the link is in the deets): https://eduadiez.github.io/GivethVWOF/view/41_10_2017/-Kwo2s-ebYY3WHC6CSB_

**Comment by GriffGreen** [comment]
making progress

**Comment by geleeroyale** [comment]
Page is available via https://fame.giveth.io
