### ISSUE TITLE
Review staging.giveth.io

### ISSUE THREAD

**Issue by geleeroyale** [Giveth/website#31]
Please review https://staging.giveth.io

**Comment by corroded** [comment]
Got some minor ones on mobile:

- spacing is a bit off in mobile bec of the line break: 
![screen shot 2017-10-24 at 8 58 10 am](https://user-images.githubusercontent.com/46548/31921014-59637276-b89f-11e7-92f7-109c7a12e872.png)

- more spacing issues regarding images
![screen shot 2017-10-24 at 8 59 26 am](https://user-images.githubusercontent.com/46548/31921026-6cbd3672-b89f-11e7-8fcc-54a4a31b1c02.png)

- github logo a bit too small for mobile
- also inconsistent text alignment. For the rest of the doc, it is left aligned, but for this section this is left aligned.
![screen shot 2017-10-24 at 9 41 34 am](https://user-images.githubusercontent.com/46548/31921051-8d5e819c-b89f-11e7-8268-93e2ee04d2c7.png)

- Not sure if this is expected: padding is a bit off on the left side for this section.
![screen shot 2017-10-24 at 9 42 38 am](https://user-images.githubusercontent.com/46548/31921064-b294223c-b89f-11e7-97e5-803d5738c171.png)

**Comment by geleeroyale** [comment]
@corroded Thanks! I am not yet through with responsive content, wanting to wait a bit for more general review. You are welcome to apply fixes anytime though ;-)

**Comment by corroded** [comment]
all good! sorry about that haha. I did say they were minor and can be ignored for now :P

**Comment by Grace-Giveth** [comment]
Hey, its taking shape! 
The title font size looks different in most sections. Could we agree on a specific size and color for titles?
Noticed the last section with the Unicorn DAC is still intact, here are the refreshed Unicorn logo.  Also, please follow the web copy text for naming conventions. 
<img width="522" alt="giveth dac logo" src="https://user-images.githubusercontent.com/18598517/31927821-ec209472-b895-11e7-913a-62d78751ebaf.png">

**Comment by Grace-Giveth** [comment]
The link to 'learn more' about DACs is set to 'Minime medium post'. Please use this link https://medium.com/giveth/giveth-introduces-decentralized-altruistic-communities-dacs-d1155a79bdc4

**Comment by geleeroyale** [comment]
@Grace-Giveth Thanks for the suggestions. I would like to know which naming conventions you mean, the text is copied in large parts from the document. I fixed some small changes like typos and stuff. Or are you referring to LiquidPledging whose naming convention is an ongoing discussion: https://github.com/Giveth/website/issues/24

**Comment by Grace-Giveth** [comment]
We are the Unicorns of Giveth 

The Giveth platform is being designed and developed by the Unicorn DAC. We are a community-led project and will not derive any direct profit from the platform. We strive to model the DAC concept as one of the first non-profit blockchain based entities. 

Learn more...https://wiki.giveth.io/dac/about/

**Comment by Grace-Giveth** [comment]
Giveth Projects
instead of our projects

**Comment by Grace-Giveth** [comment]
**#FutureOfGiving** maximizing **#blockchain4good**
if possible in bold and in a different color font

**Comment by geleeroyale** [comment]
Thank you for the feedback - Please keep it coming whenever you notice something not right with the website!
