### ISSUE TITLE
Road to Devcon3

### ISSUE THREAD

**Issue by geleeroyale** [Giveth/website#32]
Collaborative links to get the website into shape:

https://docs.google.com/document/d/19tpcEfg_q6-NCmtfx9fbWxOwwYAMrFjGT-ERZNFjLIw/edit
https://docs.google.com/presentation/d/1CcTvSXXDwZNQiXItN3ixpTciGP6-BEeRuclptX4VcNM/edit
http://giveth.webflow.io/

**Comment by Grace-Giveth** [comment]
Please make sure you use the web copy as it is and please don't change the text anymore.
