### ISSUE TITLE
Add Donate button

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/website#34]
this might be something we hack on in a couple days :-D but we have a good example that we should be able to rip off from our vault testing campaign site

**Comment by krrisis** [comment]
hear hear! where can we find that testing campaign site?

**Comment by geleeroyale** [comment]
@krrisis Griff is referring to a microsite for the vault contract: vaultcampaign.giveth.io

**Comment by GriffGreen** [comment]
sadly i think its a private repo :-P I'm going to do what i can to figure out where that code it
