### ISSUE TITLE
Copy review

### ISSUE THREAD

**Issue by krrisis** [Giveth/website#35]
- community driven --> community-driven 
- allow them to build --> allows them to build
- 2 mistakes in mobile visual (!), text to change from 'My first Video is to tell all my beautiful Givers how's this Milestone going' -->'My first video is to tell all my beautiful Givers how this Milestone is going.'
- Change 'LiquidPledging' to Liquid Pledging + x2 in visual (is already in two words under symbol anyways, let's be consistent)
- The MiniMe token --> The MiniMe Token
- Text under Giveth Donation Application is wrong, see #30 
- developed by the Giveth DAC --> developed by the Unicorn DAC (requested by Grace)
- 'The Unicorns at Giveth DAC' --> simply: 'Unicorn DAC' (requested by Grace)
- check out... --> Check out

**Comment by krrisis** [comment]
These are still open, no? 
- 2 mistakes in mobile visual (!), text to change from 'My first Video is to tell all my beautiful Givers how's this Milestone going' -->'My first video is to tell all my beautiful Givers how this Milestone is going.'
- 'The Unicorns at Giveth DAC' --> simply: 'Unicorn DAC' (requested by Grace)
- check out... --> Check out

**Comment by corroded** [comment]
Just chiming in. Was gonna fix these but checked out that everything is okay in both staging and live site except the image. Does anyone have the raw file (psd?) for that jpg so I can edit quickly?

**Comment by geleeroyale** [comment]
@corroded Thanks! Sorry - quite a lot going on during devcon, never hit enter on the issue update I wrote :-D ... Picture will change with next update
