### ISSUE TITLE
Visuals + links 

### ISSUE THREAD

**Issue by krrisis** [Giveth/website#36]
VISUALS

Logo goes under top menu on a 13" screen, shows ok on my 21,5": 

![logo](https://user-images.githubusercontent.com/6533925/31956099-b3cb218c-b8ea-11e7-8488-0b46849ff7e5.JPG)

Unicorn too close to text on 13", ok on 21,5" - maybe reduce the unicorn slightly? 

![unicorn](https://user-images.githubusercontent.com/6533925/31956232-19167d52-b8eb-11e7-8465-7e1834b4fea1.JPG)

- reduce size of github slightly on desktop? Now almost bigger than our own liquid pledging visual above this

LINKS

- https://slack.giveth.io does NOT load (also not on live site!), best to use http:// for now? (works), replace join link and logo at bottom 
- Change 'Github Giveth DApp' to 'Learn more...' + link to https://wiki.giveth.io/documentation/alpha, see also docs in #32 
- Add Reddit logo at bottom + link https://www.reddit.com/r/giveth/

**Comment by krrisis** [comment]
unicorn visual fixed but now the first 3 blocks stick to the text.. 13" & 21,5" (sorry :) )

**Comment by geleeroyale** [comment]
Thanks for re-opening. Fixed.
