### ISSUE TITLE
Missing Hero picture

### ISSUE THREAD

**Issue by Grace-Giveth** [Giveth/website#39]
No hero image on landing page

**Comment by geleeroyale** [comment]
This is interesting. Impossible for me to repeat the error. Does it load correctly now (could have been bad connection, i.e.)? If not - what browser/system did you use to get this error?

**Comment by geleeroyale** [comment]
@Grace-Giveth Do you still get the error? Else I would close this issue :-)

**Comment by Grace-Giveth** [comment]
I’m not sure, but you can close it. If this persists I will open another issue.
