### ISSUE TITLE
For devcon, we need to get rid of the fuzzy stuff and focus on DEVs

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/website#40]
I would say we remove the sections on `Campaigns that positively
change the world` and `Empowering communities` for now... that doesn't make your average ETH dev jump for joy. We can always add them back after devcon

The DAC concept is good though and can point to our DApp more, I love the pic that we have for it, though it would be nice if the text were real examples of communities and one of the communities was something about open source, and one was about decentralization, and the other two were more classical charities.

**Comment by krrisis** [comment]
I would propose to keep one block (= the first one) talking about what we do + link to the new medium post when live, we need context before you dive in. 
Agree on updating the DAC visual as you propose. Link to the Dapp is under dev corner and that's ok to me - see arguments in privteam.

**Comment by GriffGreen** [comment]
I think it turns off our targeted audience, and less text is better...

**Comment by GriffGreen** [comment]
we could move it down at least?

**Comment by krrisis** [comment]
Personally I think we need it at the top, also for devs. First: 'Who/what are we?' to grasp their attention/raise interest. Next: 'hey, discover & play with our smart contracts!' 
But number 1 can be very short, agree. Devs' corner comes waaay quicker then.

**Comment by geleeroyale** [comment]
Good discussion! Sections can be re-arranged pretty fast, so if we finally decide on a layout I can implement it right away. If we just want to do this for Devcon I can make sure the content gets changed just for the days of the conference.

**Comment by krrisis** [comment]
Personally I'd leave it as is for now. Grace has asked feedback on this text to the team. I think we need an intro so people know what we do so until someone writes anything else I'd keep this.
