### ISSUE TITLE
Proposal update for join.giveth.io 

### ISSUE THREAD

**Issue by krrisis** [Giveth/website#67]
Is it possible to change the page title to 'Join Giveth' ?
Could you also make https://join.giveth.io redirect to https://giveth.io/join/ ? (currently the secure version gives an error)

Copy proposal: 

Riot is a productivity tool with a mission to decentralize work communication. As a Decentralized Altruistic Community (DAC) we are enthusiastic supporters of this open-source initiative.
Simply join any of our rooms to start chatting! Find more info on why we are migrating and some practical tips [on our wiki](https://wiki.giveth.io/tutorials/riot-migration/).

‘Join us on Riot’
 

We started our Community on Slack, but because of its centralized and paying model we are looking into new options. If you prefer to use Slack to talk to us, sign up below!

‘Join us on Slack’

**Comment by geleeroyale** [comment]
1 - web forwarding is by default NOT SECURE - because you forward to a different site - even if that one is secure. If you want to promote secure links - you can use the subfolder versions
2 - Page title changed - THANK YOU!!
3 - Content has been switched

**Comment by geleeroyale** [comment]
Addressed in PR68
