### ISSUE TITLE
etherglade.io - independent audit

### ISSUE THREAD

**Issue by geleeroyale** [Giveth/website#86]
We are using the **etherglade plugin** on our donation page - [https://giveth.io/donate](https://giveth.io/donate)

This issue puts a bounty on auditing etherglade.js - [https://github.com/etherglade/ethergladejs](https://github.com/etherglade/ethergladejs) and the way it interacts with our website - [https://github.com/Giveth/website/blob/master/donate/index.html](https://github.com/Giveth/website/blob/master/donate/index.html)

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x3c1dc8087fc5287c42d618435db2144fe6791b44e46d69fbaebf2059963ffb79](https://etherscan.io/tx/0x3c1dc8087fc5287c42d618435db2144fe6791b44e46d69fbaebf2059963ffb79)

**Comment by geleeroyale** [comment]
We decided to remove the plugin from our site since we use MetaMask directly now.
